# AzGovViz v6_major_20220710_1
# First things first:
# 1. Mandatory: define <Management Group Id> in line 11 (e.g. be992f89-5615-4745-baca-16e5d7b72a50)
# 2. Optional: enable the schedule (line 22,23)
# Documentation: https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting
name: Build
env:
  OutputPath: wiki
  ManagementGroupId: e3615ed9-9f3a-43e1-9e3b-112a500f6652
  ScriptDir: pwsh #example: 'my folder\pwsh' or 'my folder/pwsh'
  ScriptPrereqFile: prerequisites.ps1
  ScriptFile: AzGovVizParallel.ps1
  # WebAppPublish: false #set to true and define the Web App details in the next 3 lines
  # WebAppSubscriptionId:
  # WebAppResourceGroup:
  # WebAppName:
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  actions: write
jobs:
  AzGovViz:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            enable-AzPSSession: true
      - name: Check prerequisites
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . .\$($env:ScriptDir)\$($env:ScriptPrereqFile) -OutputPath ${env:OutputPath}
          azPSVersion: "latest"
      - name: Run AzGovViz
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . .\$($env:ScriptDir)\$($env:ScriptFile) -ManagementGroupId ${env:ManagementGroupId} -SubscriptionId4AzContext ${{secrets.SUBSCRIPTION_ID}} -ScriptPath ${env:ScriptDir} -OutputPath ${env:OutputPath} -NoPIMEligibility
          azPSVersion: "latest"
      - name: Rename HTML
        uses: azure/powershell@v1
        with:
          inlineScript: |
            echo $($env:OutputPath)
            mv /home/runner/work/az-gov-viz/az-gov-viz/wiki/AzGovViz_${env:ManagementGroupId}.html /home/runner/work/az-gov-viz/az-gov-viz/index.html
            rm -rv /home/runner/work/az-gov-viz/az-gov-viz/wiki/*
            mv /home/runner/work/az-gov-viz/az-gov-viz/index.html /home/runner/work/az-gov-viz/az-gov-viz/wiki/index.html
          azPSVersion: "latest"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: az-gov-viz
          path: "/home/runner/work/az-gov-viz/az-gov-viz/wiki/"
